pipeline {
    agent any
    
    environment {
    
        DEPLOYMENT_ENVIRONMENT = 'NO_DEPLOYMENT'
        ACR_LOGINSERVER = ''
        FUTURE_ENV = 'default'
    }

    tools {
                   jdk "jdk-14"
                }

    stages {
    
    stage('Determine Environment') {
    
    steps {
                echo 'Determine Environment'

                script {

                    // Determine whether this is a test or a staging / production build              
                    switch (env.GIT_BRANCH) {
                        case 'staging':
                            GLOBAL_ENVIRONMENT = 'staging'
                            ACR_LOGINSERVER = env.ACR_DEV_LOGINSERVER
                            break
                        case 'master':
                            GLOBAL_ENVIRONMENT = 'production'
                            ACR_LOGINSERVER = env.KULA_ACR_PROD_LOGINSERVER
                            break
                        default: 
                            GLOBAL_ENVIRONMENT = 'NO_DEPLOYMENT'
                            break
                    }
                }
    }
    }
      stage('Test') {
                steps {
                     if (GLOBAL_ENVIRONMENT == 'staging') {
                        echo 'Testing..'
                        withMaven( maven: 'maven-3.6.3' ) {
                                sh 'cd future-bank-service && mvn test'
                        }
                     }

                }
            }

        stage('Build') {

            steps {
                echo env.JAVA_HOME
                echo 'Building..' + GLOBAL_ENVIRONMENT
                 script {
                    if (GLOBAL_ENVIRONMENT == 'NO_DEPLOYMENT') {
                    
                    	currentBuild.result = 'ABORTED'
                    	error('This is not develop nor master branch and should not be build')
                    } else {
                        build(GLOBAL_ENVIRONMENT)
                    }
                }
            }
        }

        
        stage('Deploy') {
            steps {
           
            script {
                  if (GLOBAL_ENVIRONMENT == 'staging') {
                    
                    sh "kubectl config use-context aks-dv-cluster-dev"
					sh "kubectl set image deployment/future-bank-service future-bank-service=${ACR_LOGINSERVER}/future-bank-service --namespace sidekiq"
					sh "kubectl rollout restart deployment/future-bank-service --namespace sidekiq"
					
                  } else {
                    sh "kubectl config use-context ubnkula"
                    sh "kubectl set image deployment/future-bank-service future-bank-service=${KULA_ACR_PROD_LOGINSERVER}/future-bank-service --namespace kula"
                    sh "kubectl rollout restart deployment/future-bank-service --namespace kula"
                  }
                }
            
           
		    
            }
        }
    }
}

def build(ENVIRONMENT) {
  echo "Hello, ${ENVIRONMENT}."
  if(ENVIRONMENT == 'staging'){
    withCredentials([usernamePassword(credentialsId: 'acr-dev-credentials', usernameVariable: 'ACR_USERNAME', passwordVariable: 'ACR_PASSWORD')]) {
    
    	 withMaven( maven: 'maven-3.6.3' ) {
    	 	withEnv(["FUTURE_ENV=staging","ACR_SERVER=${ACR_LOGINSERVER}"]){
				sh 'cd future-bank-service && mvn clean compile jib:build'
			}

    	 } 
    
    }
  
  }else{
    withCredentials([usernamePassword(credentialsId: 'kula-acr-prod-credentials', usernameVariable: 'ACR_USERNAME', passwordVariable: 'ACR_PASSWORD')]) {
     
     	withMaven( maven: 'maven-3.6.3' ) {
     		withEnv(["FUTURE_ENV=production","ACR_SERVER=${KULA_ACR_PROD_LOGINSERVER}"]){
     			sh 'cd future-bank-service && mvn clean compile jib:build'
     		}
    	 } 
    }
    
  }
  
}