package com.unionbankng.future.authorizationserver.ubnonline;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ONLINE_CUSTOMER_VALIDATION_ptt", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/DigitalServices/newibankbvnservice/newibankbvn")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ONLINECUSTOMERVALIDATIONPtt {


    /**
     * 
     * @param inputParameters
     * @return
     *     returns com.unionbankng.marcus.ubnOnlineCheck.OutputParameters
     */
    @WebMethod(operationName = "newibankbvn", action = "newibankbvn")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/newibankbvn", partName = "OutputParameters")
    public OutputParameters onlineCUSTOMERVALIDATION(
        @WebParam(name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/newibankbvn", partName = "InputParameters")
        InputParameters inputParameters);

}
