INSERT INTO tag (name,type) VALUES ('Product Design','INTEREST'),
('Graphics Design','INTEREST'),
('Mobile Development','INTEREST'),
('Digital Marketing','INTEREST'),
('Product Design','SKILLS'),
('Graphics Design','SKILLS'),
('Mobile Development','SKILLS'),
('Digital Marketing','SKILLS'),
('Product Design','COURSE_CATEGORY'),
('Graphics Design','COURSE_CATEGORY'),
('Mobile Development','COURSE_CATEGORY'),
('Digital Marketing','COURSE_CATEGORY');