spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: ${FUTURE_ENV}
  application:
    name: future-messaging-service
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
server:
  port: 8083
  error:
    include-message: always
management:
  endpoints:
    web:
      exposure:
        include: refresh
---
spring:
  config:
    activate:
      on-profile: development
    import: optional:configserver:http://localhost:8082
  cloud:
    config:
      label: develop
      profile: development
---
spring:
  config:
    activate:
      on-profile: staging
    import: optional:configserver:http://future-config-server
  cloud:
    config:
      label: staging
      profile: staging
azure:
  keyvault:
    client-id: ${KEY_VAULT_CLIENT_ID}
    client-key: ${KEY_VAULT_CLIENT_KEY}
    enabled: true
    tenant-id: ${KEY_VAULT_TENANT_ID}
    uri: ${KEY_VAULT_URL}
---
spring:
  config:
    activate:
      on-profile: production
    import: optional:configserver:http://future-config-server
  cloud:
    config:
      label: master
      profile: production
azure:
  keyvault:
    client-id: ${KEY_VAULT_CLIENT_ID}
    client-key: ${KEY_VAULT_CLIENT_KEY}
    enabled: true
    tenant-id: ${KEY_VAULT_TENANT_ID}
    uri: ${KEY_VAULT_URL}