spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: ${FUTURE_ENV}
  application:
    name: future-messaging-service
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
server:
  port: 8083
  error:
    include-message: always
management:
  endpoints:
    web:
      exposure:
        include: refresh
---
spring:
  cloud:
    config:
      label: keycloak
  config:
    import: configserver:http://localhost:8082
    activate:
      on-profile: development
---
spring:
  cloud:
    config:
      import: configserver:http://future-config-server
      label: keycloak
  config:
    activate:
      on-profile: keycloak
---

spring:
  cloud:
    config:
      import: optional:configserver:http://future-config-server
      label: master
  config:
    activate:
      on-profile: master