
package com.unionbankng.future.authorizationserver.accountenquiryprod;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EnquiryServiceOmniflowService", targetNamespace = "http://service.unionbank.com/", wsdlLocation = "https://unionworkspace.unionbankng.com/CentralOperations/AccountEnquiryOmniFlow?wsdl")
public class EnquiryServiceOmniflowService
    extends Service
{

    private final static URL ENQUIRYSERVICEOMNIFLOWSERVICE_WSDL_LOCATION;
    private final static WebServiceException ENQUIRYSERVICEOMNIFLOWSERVICE_EXCEPTION;
    private final static QName ENQUIRYSERVICEOMNIFLOWSERVICE_QNAME = new QName("http://service.unionbank.com/", "EnquiryServiceOmniflowService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://unionworkspace.unionbankng.com/CentralOperations/AccountEnquiryOmniFlow?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ENQUIRYSERVICEOMNIFLOWSERVICE_WSDL_LOCATION = url;
        ENQUIRYSERVICEOMNIFLOWSERVICE_EXCEPTION = e;
    }

    public EnquiryServiceOmniflowService() {
        super(__getWsdlLocation(), ENQUIRYSERVICEOMNIFLOWSERVICE_QNAME);
    }

    public EnquiryServiceOmniflowService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ENQUIRYSERVICEOMNIFLOWSERVICE_QNAME, features);
    }

    public EnquiryServiceOmniflowService(URL wsdlLocation) {
        super(wsdlLocation, ENQUIRYSERVICEOMNIFLOWSERVICE_QNAME);
    }

    public EnquiryServiceOmniflowService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ENQUIRYSERVICEOMNIFLOWSERVICE_QNAME, features);
    }

    public EnquiryServiceOmniflowService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EnquiryServiceOmniflowService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EnquiryService
     */
    @WebEndpoint(name = "EnquiryServicePort")
    public EnquiryService getEnquiryServicePort() {
        return super.getPort(new QName("http://service.unionbank.com/", "EnquiryServicePort"), EnquiryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EnquiryService
     */
    @WebEndpoint(name = "EnquiryServicePort")
    public EnquiryService getEnquiryServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.unionbank.com/", "EnquiryServicePort"), EnquiryService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ENQUIRYSERVICEOMNIFLOWSERVICE_EXCEPTION!= null) {
            throw ENQUIRYSERVICEOMNIFLOWSERVICE_EXCEPTION;
        }
        return ENQUIRYSERVICEOMNIFLOWSERVICE_WSDL_LOCATION;
    }

}
