
package com.unionbankng.future.authorizationserver.accountenquiry;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EnquiryService", targetNamespace = "http://service.unionbank.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EnquiryService {


    /**
     * 
     * @param acctsno
     * @return
     *     returns com.unionbankng.marcus.accountenquiry.CustomerAcctsInfo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccountSummary", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetAccountSummary")
    @ResponseWrapper(localName = "getAccountSummaryResponse", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetAccountSummaryResponse")
    public CustomerAcctsInfo getAccountSummary(
        @WebParam(name = "ACCTSNO", targetNamespace = "")
        String acctsno);

    /**
     * 
     * @param customerID
     * @return
     *     returns com.unionbankng.marcus.accountenquiry.CustomerAcctsInfo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccountSummaryByCustomerID", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetAccountSummaryByCustomerID")
    @ResponseWrapper(localName = "getAccountSummaryByCustomerIDResponse", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetAccountSummaryByCustomerIDResponse")
    public CustomerAcctsInfo getAccountSummaryByCustomerID(
        @WebParam(name = "CustomerID", targetNamespace = "")
        String customerID);

    /**
     * 
     * @param custID
     * @return
     *     returns com.unionbankng.marcus.accountenquiry.ClientDetails
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCustomerDetails", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetCustomerDetails")
    @ResponseWrapper(localName = "getCustomerDetailsResponse", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetCustomerDetailsResponse")
    public ClientDetails getCustomerDetails(
        @WebParam(name = "CustID", targetNamespace = "")
        String custID);

    /**
     * 
     * @param firstName
     * @param lastName
     * @return
     *     returns java.util.List<com.unionbankng.marcus.accountenquiry.ClientDetails>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCustomerDetailswithFirstandLast", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetCustomerDetailswithFirstandLast")
    @ResponseWrapper(localName = "getCustomerDetailswithFirstandLastResponse", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetCustomerDetailswithFirstandLastResponse")
    public List<ClientDetails> getCustomerDetailswithFirstandLast(
        @WebParam(name = "firstName", targetNamespace = "")
        String firstName,
        @WebParam(name = "lastName", targetNamespace = "")
        String lastName);

    /**
     * 
     * @param shortName
     * @return
     *     returns java.util.List<com.unionbankng.marcus.accountenquiry.ClientDetails>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCustomerDetailsbyShortName", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetCustomerDetailsbyShortName")
    @ResponseWrapper(localName = "getCustomerDetailsbyShortNameResponse", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetCustomerDetailsbyShortNameResponse")
    public List<ClientDetails> getCustomerDetailsbyShortName(
        @WebParam(name = "shortName", targetNamespace = "")
        String shortName);

    /**
     * 
     * @param phoneNumber
     * @return
     *     returns java.util.List<com.unionbankng.marcus.accountenquiry.ClientDetails>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCustomerDetailsbyPhoneNumber", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetCustomerDetailsbyPhoneNumber")
    @ResponseWrapper(localName = "getCustomerDetailsbyPhoneNumberResponse", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetCustomerDetailsbyPhoneNumberResponse")
    public List<ClientDetails> getCustomerDetailsbyPhoneNumber(
        @WebParam(name = "phoneNumber", targetNamespace = "")
        String phoneNumber);

    /**
     * 
     * @param acctsno
     * @return
     *     returns com.unionbankng.marcus.accountenquiry.CustomerAcctsDetail
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCustomerAcctsDetail", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetCustomerAcctsDetail")
    @ResponseWrapper(localName = "getCustomerAcctsDetailResponse", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetCustomerAcctsDetailResponse")
    public CustomerAcctsDetail getCustomerAcctsDetail(
        @WebParam(name = "ACCTSNO", targetNamespace = "")
        String acctsno);

    /**
     * 
     * @param acctsno
     * @return
     *     returns com.unionbankng.marcus.accountenquiry.ClientDetails
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCustomerDetailsWithAcctNumber", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetCustomerDetailsWithAcctNumber")
    @ResponseWrapper(localName = "getCustomerDetailsWithAcctNumberResponse", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetCustomerDetailsWithAcctNumberResponse")
    public ClientDetails getCustomerDetailsWithAcctNumber(
        @WebParam(name = "ACCTSNO", targetNamespace = "")
        String acctsno);

    /**
     * 
     * @param typInstr
     * @param refInstrNoStno
     * @param codRoutingInstr
     * @param amtInstr
     * @return
     *     returns java.util.List<com.unionbankng.marcus.accountenquiry.ManagersChequeDetails>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMangersChequeStatusInfo", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetMangersChequeStatusInfo")
    @ResponseWrapper(localName = "getMangersChequeStatusInfoResponse", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetMangersChequeStatusInfoResponse")
    public List<ManagersChequeDetails> getMangersChequeStatusInfo(
        @WebParam(name = "typ_instr", targetNamespace = "")
        String typInstr,
        @WebParam(name = "cod_routing_instr", targetNamespace = "")
        String codRoutingInstr,
        @WebParam(name = "ref_instr_no_stno", targetNamespace = "")
        String refInstrNoStno,
        @WebParam(name = "amt_instr", targetNamespace = "")
        String amtInstr);

    /**
     * 
     * @param typInstr
     * @param refInstrNoStno
     * @param codRoutingInstr
     * @param amtInstr
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMangersChequeStatus", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetMangersChequeStatus")
    @ResponseWrapper(localName = "getMangersChequeStatusResponse", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetMangersChequeStatusResponse")
    public String getMangersChequeStatus(
        @WebParam(name = "typ_instr", targetNamespace = "")
        String typInstr,
        @WebParam(name = "cod_routing_instr", targetNamespace = "")
        String codRoutingInstr,
        @WebParam(name = "ref_instr_no_stno", targetNamespace = "")
        String refInstrNoStno,
        @WebParam(name = "amt_instr", targetNamespace = "")
        String amtInstr);

    /**
     * 
     * @param strAccountNo
     * @param strChequeNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getChequeNumberInquiry", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetChequeNumberInquiry")
    @ResponseWrapper(localName = "getChequeNumberInquiryResponse", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetChequeNumberInquiryResponse")
    public String getChequeNumberInquiry(
        @WebParam(name = "strAccountNo", targetNamespace = "")
        String strAccountNo,
        @WebParam(name = "strChequeNo", targetNamespace = "")
        String strChequeNo);

    /**
     * 
     * @param acctno
     * @param enddate
     * @param startdate
     * @return
     *     returns com.unionbankng.marcus.accountenquiry.CustomerAcctsWithTransactionInfoWithBranch
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccountSummaryANDTransactions", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetAccountSummaryANDTransactions")
    @ResponseWrapper(localName = "getAccountSummaryANDTransactionsResponse", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetAccountSummaryANDTransactionsResponse")
    public CustomerAcctsWithTransactionInfoWithBranch getAccountSummaryANDTransactions(
        @WebParam(name = "ACCTNO", targetNamespace = "")
        String acctno,
        @WebParam(name = "STARTDATE", targetNamespace = "")
        String startdate,
        @WebParam(name = "ENDDATE", targetNamespace = "")
        String enddate);

    /**
     * 
     * @param acctno
     * @param enddate
     * @param startdate
     * @return
     *     returns com.unionbankng.marcus.accountenquiry.CustomerAcctsWithTranInfoWithBranchGeneric
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccountSummaryANDTxnGeneric", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetAccountSummaryANDTxnGeneric")
    @ResponseWrapper(localName = "getAccountSummaryANDTxnGenericResponse", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetAccountSummaryANDTxnGenericResponse")
    public CustomerAcctsWithTranInfoWithBranchGeneric getAccountSummaryANDTxnGeneric(
        @WebParam(name = "ACCTNO", targetNamespace = "")
        String acctno,
        @WebParam(name = "STARTDATE", targetNamespace = "")
        String startdate,
        @WebParam(name = "ENDDATE", targetNamespace = "")
        String enddate);

    /**
     * 
     * @param custID
     * @return
     *     returns com.unionbankng.marcus.accountenquiry.AccountMemoInfo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccounMemoInfo", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetAccounMemoInfo")
    @ResponseWrapper(localName = "getAccounMemoInfoResponse", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetAccounMemoInfoResponse")
    public AccountMemoInfo getAccounMemoInfo(
        @WebParam(name = "CustID", targetNamespace = "")
        String custID);

    /**
     * 
     * @param acctnumber
     * @return
     *     returns com.unionbankng.marcus.accountenquiry.AccountSearchInfo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccountSerachByAccountNumber", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetAccountSerachByAccountNumber")
    @ResponseWrapper(localName = "getAccountSerachByAccountNumberResponse", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetAccountSerachByAccountNumberResponse")
    public AccountSearchInfo getAccountSerachByAccountNumber(
        @WebParam(name = "ACCTNUMBER", targetNamespace = "")
        String acctnumber);

    /**
     * 
     * @param accttitle
     * @return
     *     returns com.unionbankng.marcus.accountenquiry.AccountSearchInfo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccountSerachByAccountTitle", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetAccountSerachByAccountTitle")
    @ResponseWrapper(localName = "getAccountSerachByAccountTitleResponse", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetAccountSerachByAccountTitleResponse")
    public AccountSearchInfo getAccountSerachByAccountTitle(
        @WebParam(name = "ACCTTITLE", targetNamespace = "")
        String accttitle);

    /**
     * 
     * @param accttitle
     * @param brncode
     * @return
     *     returns com.unionbankng.marcus.accountenquiry.AccountSearchInfo
     */
    @WebMethod(operationName = "AccountSearchByAcctTitleAndBranchCode")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "AccountSearchByAcctTitleAndBranchCode", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.AccountSearchByAcctTitleAndBranchCode")
    @ResponseWrapper(localName = "AccountSearchByAcctTitleAndBranchCodeResponse", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.AccountSearchByAcctTitleAndBranchCodeResponse")
    public AccountSearchInfo accountSearchByAcctTitleAndBranchCode(
        @WebParam(name = "ACCTTITLE", targetNamespace = "")
        String accttitle,
        @WebParam(name = "BRNCODE", targetNamespace = "")
        String brncode);

    /**
     * 
     * @param acctno
     * @param tranDate
     * @param rowId
     * @return
     *     returns com.unionbankng.marcus.accountenquiry.SingleTransactionDetails
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSingleTransactionDetails", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetSingleTransactionDetails")
    @ResponseWrapper(localName = "getSingleTransactionDetailsResponse", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetSingleTransactionDetailsResponse")
    public SingleTransactionDetails getSingleTransactionDetails(
        @WebParam(name = "ACCTNO", targetNamespace = "")
        String acctno,
        @WebParam(name = "TranDate", targetNamespace = "")
        String tranDate,
        @WebParam(name = "RowId", targetNamespace = "")
        String rowId);

    /**
     * 
     * @param createdBy
     * @param serverIp
     * @param eventRef
     * @param event
     * @param staffId
     */
    @WebMethod
    @RequestWrapper(localName = "createLog", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.CreateLog")
    @ResponseWrapper(localName = "createLogResponse", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.CreateLogResponse")
    public void createLog(
        @WebParam(name = "staffId", targetNamespace = "")
        String staffId,
        @WebParam(name = "event", targetNamespace = "")
        String event,
        @WebParam(name = "createdBy", targetNamespace = "")
        String createdBy,
        @WebParam(name = "eventRef", targetNamespace = "")
        String eventRef,
        @WebParam(name = "serverIp", targetNamespace = "")
        String serverIp);

    /**
     * 
     * @param endDate
     * @param userId
     * @param startDate
     * @return
     *     returns java.util.List<com.unionbankng.marcus.accountenquiry.AuditInformation>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getActivityLogSpecific", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetActivityLogSpecific")
    @ResponseWrapper(localName = "getActivityLogSpecificResponse", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetActivityLogSpecificResponse")
    public List<AuditInformation> getActivityLogSpecific(
        @WebParam(name = "userId", targetNamespace = "")
        String userId,
        @WebParam(name = "startDate", targetNamespace = "")
        String startDate,
        @WebParam(name = "endDate", targetNamespace = "")
        String endDate);

    /**
     * 
     * @param endDate
     * @param startDate
     * @return
     *     returns java.util.List<com.unionbankng.marcus.accountenquiry.AuditInformation>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getActivityLog", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetActivityLog")
    @ResponseWrapper(localName = "getActivityLogResponse", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetActivityLogResponse")
    public List<AuditInformation> getActivityLog(
        @WebParam(name = "startDate", targetNamespace = "")
        String startDate,
        @WebParam(name = "endDate", targetNamespace = "")
        String endDate);

    /**
     * 
     * @return
     *     returns java.util.List<com.unionbankng.marcus.accountenquiry.BranchList>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBranchList", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetBranchList")
    @ResponseWrapper(localName = "getBranchListResponse", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetBranchListResponse")
    public List<BranchList> getBranchList();

    /**
     * 
     * @param accountNumber
     * @return
     *     returns java.util.List<com.unionbankng.marcus.accountenquiry.LoanList>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLoanList", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetLoanList")
    @ResponseWrapper(localName = "getLoanListResponse", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetLoanListResponse")
    public List<LoanList> getLoanList(
        @WebParam(name = "accountNumber", targetNamespace = "")
        String accountNumber);

    /**
     * 
     * @param accountNumber
     * @return
     *     returns java.util.List<com.unionbankng.marcus.accountenquiry.OverdraftList>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOverDraftList", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetOverDraftList")
    @ResponseWrapper(localName = "getOverDraftListResponse", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetOverDraftListResponse")
    public List<OverdraftList> getOverDraftList(
        @WebParam(name = "accountNumber", targetNamespace = "")
        String accountNumber);

    /**
     * 
     * @param cic
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getcicRecord", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetcicRecord")
    @ResponseWrapper(localName = "getcicRecordResponse", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetcicRecordResponse")
    public String getcicRecord(
        @WebParam(name = "cic", targetNamespace = "")
        String cic);

    /**
     * 
     * @return
     *     returns java.util.List<com.unionbankng.marcus.accountenquiry.ProductList>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductList", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetProductList")
    @ResponseWrapper(localName = "getProductListResponse", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetProductListResponse")
    public List<ProductList> getProductList();

    /**
     * 
     * @param accountNo
     * @return
     *     returns java.util.List<com.unionbankng.marcus.accountenquiry.AccountMandate>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccountMandate", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetAccountMandate")
    @ResponseWrapper(localName = "getAccountMandateResponse", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetAccountMandateResponse")
    public List<AccountMandate> getAccountMandate(
        @WebParam(name = "account_no", targetNamespace = "")
        String accountNo);

    /**
     * 
     * @param customerNo
     * @return
     *     returns java.util.List<com.unionbankng.marcus.accountenquiry.CustomerMandate>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCustomerMandate", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetCustomerMandate")
    @ResponseWrapper(localName = "getCustomerMandateResponse", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetCustomerMandateResponse")
    public List<CustomerMandate> getCustomerMandate(
        @WebParam(name = "customer_no", targetNamespace = "")
        String customerNo);

    /**
     * 
     * @param accountNo
     * @param instrumentNo
     * @param controlNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getChqUtilization", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetChqUtilization")
    @ResponseWrapper(localName = "getChqUtilizationResponse", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetChqUtilizationResponse")
    public String getChqUtilization(
        @WebParam(name = "account_no", targetNamespace = "")
        String accountNo,
        @WebParam(name = "instrument_no", targetNamespace = "")
        String instrumentNo,
        @WebParam(name = "control_no", targetNamespace = "")
        String controlNo);

    /**
     * 
     * @param everSuiteFiledOrWroffBur
     * @param noOfDependents
     * @param appliedLtv
     * @param categoryOfCurrentEmployer
     * @param gender
     * @param noOfYearAtCurrEmployer
     * @param contactability
     * @param applicationNo
     * @param grossAnnualIncome
     * @param loanTermRequested
     * @param monthlyRepaymentSalaryAmt
     * @param ever90InPast12MthsInBur
     * @param applicantAge
     * @param totalLoanOutstVsGrsAnInc
     * @param accountNo
     * @param highestAttainedEducationLev
     * @param repaymentBankAcctDomicile
     * @param homeResidentDuration
     * @param designation
     * @param homeType
     * @param maritalStatus
     * @return
     *     returns com.unionbankng.marcus.accountenquiry.LoanDetailsResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getloanScore", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetloanScore")
    @ResponseWrapper(localName = "getloanScoreResponse", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetloanScoreResponse")
    public LoanDetailsResponse getloanScore(
        @WebParam(name = "application_no", targetNamespace = "")
        String applicationNo,
        @WebParam(name = "account_no", targetNamespace = "")
        String accountNo,
        @WebParam(name = "applicant_age", targetNamespace = "")
        Integer applicantAge,
        @WebParam(name = "marital_status", targetNamespace = "")
        Integer maritalStatus,
        @WebParam(name = "home_type", targetNamespace = "")
        Integer homeType,
        @WebParam(name = "gender", targetNamespace = "")
        Integer gender,
        @WebParam(name = "home_resident_duration", targetNamespace = "")
        Integer homeResidentDuration,
        @WebParam(name = "no_of_dependents", targetNamespace = "")
        Integer noOfDependents,
        @WebParam(name = "gross_annual_income", targetNamespace = "")
        Integer grossAnnualIncome,
        @WebParam(name = "highest_attained_education_lev", targetNamespace = "")
        Integer highestAttainedEducationLev,
        @WebParam(name = "applied_ltv", targetNamespace = "")
        Integer appliedLtv,
        @WebParam(name = "contactability", targetNamespace = "")
        Integer contactability,
        @WebParam(name = "repayment_bank_acct_domicile", targetNamespace = "")
        Integer repaymentBankAcctDomicile,
        @WebParam(name = "loan_term_requested", targetNamespace = "")
        Integer loanTermRequested,
        @WebParam(name = "monthly_repayment_salary_amt", targetNamespace = "")
        Integer monthlyRepaymentSalaryAmt,
        @WebParam(name = "designation", targetNamespace = "")
        Integer designation,
        @WebParam(name = "category_of_current_employer", targetNamespace = "")
        Integer categoryOfCurrentEmployer,
        @WebParam(name = "no_of_year_at_curr_employer", targetNamespace = "")
        Integer noOfYearAtCurrEmployer,
        @WebParam(name = "ever_90_in_past_12_mths_in_bur", targetNamespace = "")
        Integer ever90InPast12MthsInBur,
        @WebParam(name = "ever_suite_filed_or_wroff_bur", targetNamespace = "")
        Integer everSuiteFiledOrWroffBur,
        @WebParam(name = "total_loan_outst_vs_grs_an_inc", targetNamespace = "")
        Integer totalLoanOutstVsGrsAnInc);

    /**
     * 
     * @param terminalId
     * @return
     *     returns com.unionbankng.marcus.accountenquiry.GlTerminalDetails
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGlForTerminal", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetGlForTerminal")
    @ResponseWrapper(localName = "getGlForTerminalResponse", targetNamespace = "http://service.unionbank.com/", className = "com.unionbankng.marcus.accountenquiry.GetGlForTerminalResponse")
    public GlTerminalDetails getGlForTerminal(
        @WebParam(name = "terminalId", targetNamespace = "")
        String terminalId);

}
