
package com.unionbankng.future.authorizationserver.accountenquiry;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EnquiryServicePortBindingQSService", targetNamespace = "http://service.unionbank.com/", wsdlLocation = "https://ubnsandbox.unionbankng.com/UBN/AccountEnquiry/ProxyServices/AccountEnquiryPS?wsdl")
public class EnquiryServicePortBindingQSService
    extends Service
{

    private final static URL ENQUIRYSERVICEPORTBINDINGQSSERVICE_WSDL_LOCATION;
    private final static WebServiceException ENQUIRYSERVICEPORTBINDINGQSSERVICE_EXCEPTION;
    private final static QName ENQUIRYSERVICEPORTBINDINGQSSERVICE_QNAME = new QName("http://service.unionbank.com/", "EnquiryServicePortBindingQSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {	
            url = new URL("https://ubnsandbox.unionbankng.com/UBN/AccountEnquiry/ProxyServices/AccountEnquiryPS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ENQUIRYSERVICEPORTBINDINGQSSERVICE_WSDL_LOCATION = url;
        ENQUIRYSERVICEPORTBINDINGQSSERVICE_EXCEPTION = e;
    }

    public EnquiryServicePortBindingQSService() {
        super(__getWsdlLocation(), ENQUIRYSERVICEPORTBINDINGQSSERVICE_QNAME);
    }

    public EnquiryServicePortBindingQSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ENQUIRYSERVICEPORTBINDINGQSSERVICE_QNAME, features);
    }

    public EnquiryServicePortBindingQSService(URL wsdlLocation) {
        super(wsdlLocation, ENQUIRYSERVICEPORTBINDINGQSSERVICE_QNAME);
    }

    public EnquiryServicePortBindingQSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ENQUIRYSERVICEPORTBINDINGQSSERVICE_QNAME, features);
    }

    public EnquiryServicePortBindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EnquiryServicePortBindingQSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EnquiryService
     */
    @WebEndpoint(name = "EnquiryServicePortBindingQSPort")
    public EnquiryService getEnquiryServicePortBindingQSPort() {
        return super.getPort(new QName("http://service.unionbank.com/", "EnquiryServicePortBindingQSPort"), EnquiryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EnquiryService
     */
    @WebEndpoint(name = "EnquiryServicePortBindingQSPort")
    public EnquiryService getEnquiryServicePortBindingQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.unionbank.com/", "EnquiryServicePortBindingQSPort"), EnquiryService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ENQUIRYSERVICEPORTBINDINGQSSERVICE_EXCEPTION!= null) {
            throw ENQUIRYSERVICEPORTBINDINGQSSERVICE_EXCEPTION;
        }
        return ENQUIRYSERVICEPORTBINDINGQSSERVICE_WSDL_LOCATION;
    }

}
