spring:
  profiles:
    active: ${FUTURE_ENV}
  application:
    name: future-gateway
server:
  port: 8080
eureka:
  client:
    register-with-eureka: true

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000
ribbon:
  ReadTimeout: 10000

---

spring:
  profiles: development
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8081/eureka}
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    authorization-server:
      path: /authserv/**
      service-id: authorization-server
    job-service:
      path: /jobserv/**
      service-id: job-service


---
spring:
  profiles: staging
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://future-eureka-server/eureka}
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    authorization-server:
      path: /authserv/**
      url: http://future-auth-server
    job-service:
      path: /jobserv/**
      url: http://future-job-service

---
spring:
  profiles: production
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://future-eureka-server/eureka}
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    authorization-server:
      path: /authserv/**
      url: http://future-auth-server
    job-service:
      path: /jobserv/**
      url: http://future-job-service

