spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: ${FUTURE_ENV}
  application:
    name: future-utility-service
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
server:
  port: 8085
grpc:
  server:
    port: 9090

management:
  endpoints:
    web:
      exposure:
        include: refresh
---
spring:
  config:
    activate:
      on-profile: development
    import: optional:configserver:http://localhost:8082
  cloud:
    config:
      label: develop
      profile: development
---
spring:
  config:
    activate:
      on-profile: staging
    import: optional:configserver:http://future-config-server
  cloud:
    config:
      label: staging
      profile: staging
azure:
  keyvault:
    keyvault1:
      client-id: ${KEY_VAULT_CLIENT_ID}
      client-key: ${KEY_VAULT_CLIENT_KEY}
      tenant-id: ${KEY_VAULT_TENANT_ID}
      uri: ${KEY_VAULT_URL}
    keyvault2:
      client-id: ${KEY_VAULT_CLIENT_ID}
      client-key: ${KEY_VAULT_CLIENT_KEY}
      tenant-id: ${KEY_VAULT_TENANT_ID}
      uri: ${KEY_VAULT2_URL}
    order: keyvault1,keyvault2
---
spring:
  config:
    activate:
      on-profile: production
    import: optional:configserver:http://future-config-server
  cloud:
    config:
      label: master
      profile: production
